### PR TITLE
Allow updating selectedValue and options via props

### PR DESCRIPTION
**Pull request by kevinhughes27**
First I just want to say thanks for this component it was exactly what I wanted!

I'm using this component inside a form where it is bound to another input (if you change one the other changes as well). I had to make the following changes to have `react-responsive-select` update if new props are received and then I had to debounce my change handler because this update triggers an event from `react-responsive-select` as well.

I'm not suggesting to merge this code as is since its not a complete (probably breaks for multiselect) or proper solution (the debounce issue). What are your thoughts on how we should approach this?

### CODE REVIEW

**Comment by benbowes** [comment]
Cheers @kevinhughes27 this is interesting. I will have a look and get back soon.

**Comment by benbowes** [comment]
Hi @kevinhughes27 does this resemble what you are trying to do? https://codepen.io/benbowes/pen/baKoBQ

If it does, then I see what you mean and would want to do something about it.

**Comment by benbowes** [comment]
@kevinhughes27 I am wondering whether it would be useful to expose a prop that would give the ability to update any state on the fly, allowing it to be fully controllable - any thoughts on this?

Provide some way to update all of the state via a container component. Allowing the setting of altered, open, change of options etc...
https://github.com/benbowes/react-responsive-select/blob/master/src/reducers/reducer.js#L12-L35

Any thoughts on this?

**Comment by kevinhughes27** [comment]
Thanks @benbowes the codepen does resemble what I am trying to do. Having the input be fully controllable sounds like a good idea to me. Let me know if you want some help!

**Comment by benbowes** [comment]
@kevinhughes27 some help would be great. Having `state.altered` tweak-able via a prop would be a great start.

**Comment by benbowes** [comment]
I had a look over the weekend and got to this https://github.com/benbowes/react-responsive-select/pull/55 which might help

**Comment by benbowes** [comment]
Relates to https://github.com/benbowes/react-responsive-select/pull/55

**Pull request closed without merging**
